name: Build jacoco-filter Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean jacoco_filter.spec

      - name: Rename artifact
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/jacoco-filter.exe dist/jacoco-filter-win.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv dist/jacoco-filter dist/jacoco-filter-macos
          else
            mv dist/jacoco-filter dist/jacoco-filter-linux
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-filter-${{ runner.os }}
          path: dist/*
